services:
  db:
    build: 
      context: .
      dockerfile: dockerfile.database
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/main
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb
    networks:
      - api

  app:
    build: 
      context: .
      target: development
    env_file: .env.development
    container_name: api-app
    restart: always
    depends_on: [db]
    ports:
      - '80:80'
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist

    networks:
      - api

networks:
  api:
    driver: bridge
    name: nest-shared-network

